=== CoryAlbrecht/cartouche/assets/xml/schemas/i18n.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://maps.hanfastolfe.com/cartouche/schemas/i18n/1.0"
    xmlns:ci18n="http://maps.hanfastolfe.com/cartouche/schemas/i18n/1.0"
    elementFormDefault="qualified">

    <xs:element name="localization">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="string" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="locale" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>

</xs:schema>

=== CoryAlbrecht/cartouche/assets/xml/i18n/en.xml
<?xml version="1.0" encoding="UTF-8"?>
<ci18n:localization xmlns="http://maps.hanfastolfe.com/cartouche/schemas/i18n/1.0"
    xmlns:ci18n="http://maps.hanfastolfe.com/cartouche/schemas/i18n/1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maps.hanfastolfe.com/cartouche/schemas/i18n/1.0 ../schemas/i18n.xsd"
    locale="en">
    <!-- File Menu -->
    <string name="new_project">New Project...</string>
    <string name="open_project">Open Project...</string>
    <string name="save_project">Save Project</string>
    <string name="save_as_project">Save Project As...</string>
    <string name="add_layers">Add Layers...</string>
    <string name="new_map_view">New Map View</string>
    <string name="pan_tool">Drag Map Canvas (Pan)</string>
    <string name="toggle_layers_widget">Toggle Layers Widget</string>
    <string name="exit_app">Exit</string>
    <!-- Edit Menu -->
    <string name="undo_action">Undo</string>
    <string name="redo_action">Redo</string>
    <string name="cut">Cut</string>
    <string name="copy">Copy</string>
    <string name="paste">Paste</string>
    <string name="edit_layer_attributes">Edit Layer Attributes...</string>
    <string name="open_preferences">Open Preferences...</string>
    <!-- Miscellaneous -->
    <string name="shortcut_save">Press <kbd>Ctrl</kbd> + <kbd>S</kbd> to save.</string>
    <!-- Layer Tree & Modal Dialogs -->
    <string name="remove_layer_title">Remove Layer</string>
    <string name="remove_group_title">Remove Group</string>
    <string name="remove_items_title">Remove Selected Items</string>
    <string name="remove_layer_prompt">Are you sure you want to remove layer '{0}' from the project?</string>
    <string name="remove_group_prompt">Are you sure you want to remove group '{0}'? This will also remove all items inside it.</string>
    <string name="remove_items_prompt">Are you sure you want to remove the {0} selected items from the project? Any groups will also have their contents removed.</string>
    <string name="dialog_remove">Remove</string>
    <string name="dialog_cancel">Cancel</string>
    <string name="create_group">Create Group</string>
    <string name="remove_layer">Remove Layer</string>
    <string name="remove_group">Remove Group</string>
    <string name="remove_selected_items">Remove Selected Items</string>
</ci18n:localization>
